### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rjfarber**
Added import wavfile from scipy to the basic example to obviate people searching how to do so in the future :)

### CODE REVIEW

**Review by timsainb — CHANGES_REQUESTED** [review]
Lets add this too. 

wavefile.write("mywav_reduced_noise.wav", rate, reduced_noise)

**Comment by rjfarber** [comment]
Okay, I think this is done now.

**Comment by rjfarber** [comment]
Hmm, that didn't actually merge it.

**Comment by timsainb** [comment]
It's merged. Thanks!

**Pull request merged**
